import type { IScan } from '../db/models/Scan';

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

export function generateHtmlReport(scan: IScan): string {
  const score = scan.accessibilityScore ?? '—';
  const cost = scan.llmCostUsd != null ? `$${scan.llmCostUsd.toFixed(4)}` : '—';
  const tokens = scan.llm?.usage?.totalTokens ?? 0;

  const violationRows = scan.violations
    .map((v) => {
      const exp = v.explanation;
      const sev = exp?.severity || v.impact || 'moderate';
      const conf = exp?.confidence || 'low';
      return `
      <article class="violation">
        <header>
          <h3>${escapeHtml(v.id)} <span class="badge ${sev}">${sev}</span></h3>
          <p class="help">${escapeHtml(v.help)}</p>
          <p class="confidence ${conf}">${conf} confidence${exp?.isFallback ? ' · fallback' : ''}</p>
        </header>
        ${exp ? `
        <p><strong>What's wrong:</strong> ${escapeHtml(exp.plainLanguageExplanation)}</p>
        <p><strong>Why it matters:</strong> ${escapeHtml(exp.whyItMatters)}</p>
        ` : ''}
        <div class="code-grid">
          <div><h4>Before</h4><pre>${escapeHtml(v.nodes[0]?.html || '')}</pre></div>
          <div><h4>Suggested fix</h4><pre>${escapeHtml(exp?.suggestedFixCode || '')}</pre></div>
        </div>
      </article>`;
    })
    .join('');

  const comparison = scan.comparison
    ? `<p class="comparison">${scan.comparison.fixed} fixed · ${scan.comparison.new} new · ${scan.comparison.unchanged} unchanged vs previous scan</p>`
    : '';

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <title>AuditAlly Report — ${escapeHtml(scan.url)}</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 900px; margin: 2rem auto; padding: 0 1rem; color: #1a1a1a; }
    h1 { font-size: 1.5rem; }
    .meta { color: #555; font-size: 0.9rem; margin-bottom: 1.5rem; }
    .score { font-size: 2rem; font-weight: bold; color: #0d7377; }
    .violation { border: 1px solid #ddd; border-radius: 8px; padding: 1rem; margin: 1rem 0; }
    .badge { font-size: 0.75rem; padding: 0.15rem 0.5rem; border-radius: 4px; text-transform: uppercase; }
    .critical { background: #fee; color: #900; }
    .serious { background: #fed; color: #a60; }
    .moderate { background: #ffd; color: #880; }
    .minor { background: #efe; color: #060; }
    pre { background: #222; color: #eee; padding: 0.75rem; overflow: auto; font-size: 0.8rem; border-radius: 4px; }
    .code-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; }
    @media print { body { margin: 0; } }
  </style>
</head>
<body>
  <h1>AuditAlly Accessibility Report</h1>
  <p class="meta">
    <strong>URL:</strong> ${escapeHtml(scan.url)}<br/>
    <strong>Scanned:</strong> ${scan.scannedAt.toISOString()}<br/>
    <strong>Violations:</strong> ${scan.violationCount}<br/>
    <strong>LLM tokens:</strong> ${tokens} · <strong>Est. cost:</strong> ${cost}
  </p>
  <p class="score">Accessibility score: ${score}/100</p>
  ${comparison}
  ${violationRows || '<p>No violations found.</p>'}
  <footer class="meta"><p>Generated by AuditAlly — axe-core detection + AI interpretation</p></footer>
</body>
</html>`;
}
